import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import React, { useState } from "react";

const Reminders: React.FC = () => {
  const { data: reminders, isLoading } = trpc.reminder.getAll.useQuery();
  const [isDone, setIsDone] = useState(false);

  if (isLoading) return <div>Fetching reminders...</div>;

  return (
    <div>
      {reminders?.map((reminder, index) => {
        return (
          <div key={index} className="p-4">
            <p
              className={`cursor-pointer text-xl ${
                reminder.checked && "line-through"
              }`}
            >
              <i onClick={() => (reminder.checked = true)}>{reminder.text}</i>
            </p>
          </div>
        );
      })}
    </div>
  );
};

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  if (status === "loading") {
    return <main className="flex flex-col items-center pt-4">Loading...</main>;
  }

  return (
    <>
      <Head>
        <title>Reminder List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col p-12">
        <section className="flex w-full items-center justify-between">
          <h1 className="rounded-md border border-violet-600 p-3 text-2xl">
            {session && session.user?.name + "'s"} Reminder List
          </h1>

          <div className="flex gap-4">
            {session ? (
              <>
                <button className="rounded-md bg-violet-600 p-3 text-2xl transition-colors hover:bg-violet-500">
                  + Add Reminder
                </button>
                <button
                  className="rounded-md bg-violet-600 p-3 text-2xl transition-colors hover:bg-violet-500"
                  onClick={() => signOut()}
                >
                  Logout
                </button>
              </>
            ) : (
              <button
                className="rounded-md bg-violet-600 p-3 text-2xl transition-colors hover:bg-violet-500"
                onClick={() => signIn("discord")}
              >
                Login with Discord
              </button>
            )}
          </div>
        </section>
        {session && (
          <div className="mt-5 rounded-md border border-violet-600">
            <Reminders />
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
